cat/urls.py
"""Defines URL patterns for kisik"""

from django.urls import path

from . import views

app_name = 'cat'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Path that shows all topics
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry')
]

kisik/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('cat.urls')),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth url
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register')
]

cat/models.py
from django.db import models

# Create your models here.


class Topic(models.Model):

    """A topic that user is learning about"""

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        """A string representation of the model"""

        return self.text


class Entry(models.Model):

    """Something specific about the topic"""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):

        """A string representation of the model"""

        len_text = len(self.text[:])
        if len_text <= 50:
            return f'{self.text[:]}'
        else:
            return f'{self.text[:50]}...'

users/models.py
from django.db import models

# Create your models here.

cat/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

cat/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):

    """The homepage for kisik"""

    return render(request, 'cat/index.html')

@login_required
def topics(request):

    """Shows all topics"""

    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}

    return render(request, 'cat/topics.html', context)

@login_required
def topic(request, topic_id):

    """Shows a single topic and its entries"""

    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}

    return render(request, 'cat/topic.html', context)

@login_required
def new_topic(request):

    """Adding a new topic"""

    if request.method != 'POST':
        # No data submitted; create a blank form
        form = TopicForm()
    else:
        # POST data submitted, process data
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('cat:topics')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'cat/new_topic.html', context)

@login_required
def new_entry(request, topic_id):

    """Adding a new entry for the particular topic"""

    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted; create a blank form
        form = EntryForm()
    else:
        # POST data submitted; process data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('cat:topic', topic_id=topic_id)

    # Display a blank or invalid form
    context = {'topic': topic, 'form': form}
    return render(request, 'cat/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):

    """Editing the entry from the list"""

    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('cat:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'cat/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):

    """Register a new user"""

    if request.method != 'POST':
        # Display blank registration form
        form = UserCreationForm()
    else:
        # Process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to the home page
            login(request, new_user)
            return redirect('cat:index')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

cat/templates/cat/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>kisik</title>
</head>
<body>
<p>
    <a href="{% url 'cat:index' %}">KISIK</a> -
    <a href="{% url 'cat:topics' %}">Topics</a> -
    {% if user.is_authenticated %}
      Hello, {{ user.username }} -
      <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
      <a href="{% url 'users:register' %}">Register</a> -
      <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
    </p>
{% block content %}{% endblock content %}
</body>
</html>

cat/templates/cat/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "cat/base.html" %}
</head>
<body>
{% block content %}

  <p><a href="{% url 'cat:topic' topic.id %}">{{ topic }}</a></p>

  <p>Please, edit the entry:</p>

  <form action="{% url 'cat:edit_entry' entry.id %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">Save changes</button>
  </form>

{% endblock content %}
</body>
</html>

cat/templates/cat/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "cat/base.html" %}
</head>
<body>
{% block content %}
    <p>Hello, stranger! Welcome to the KISIK!</p>
    <p>Kisik is the place where you can share your love to our little fluffy friends - cats.</p>
    <p>Feel free to write everything you want to tell us about them!</p>
{% endblock content %}
</body>
</html>

cat/templates/cat/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "cat/base.html" %}
</head>
<body>
{% block content %}

  <p><a href="{% url 'cat:topic' topic.id %}">{{ topic }}</a></p>

  <p>Please, write the new entry:</p>

  <form action="{% url 'cat:new_entry' topic.id %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">Save entry</button>
  </form>

{% endblock content %}
</body>
</html>

cat/templates/cat/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "cat/base.html" %}
</head>
<body>
{% block content %}
  <p>Please, enter the name of the new topic:</p>

  <form action="{% url 'cat:new_topic' %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">Add topic</button>
  </form>

{% endblock content %}
</body>
</html>

cat/templates/cat/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends 'cat/base.html' %}
</head>
<body>
{% block content %}
  <p>Topic: {{ topic }}</p>

  <p>Entries:</p>
  <p>
    <a href="{% url 'cat:new_entry' topic.id %}">Create new entry</a>
  </p>
  <ul>
    {% for entry in entries %}
      <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
        <p>
          <a href="{% url 'cat:edit_entry' entry.id %}">Edit entry</a>
        </p>
      </li>
    {% empty %}
      <li>There are no entries for this topic yet :(</li>
    {% endfor %}
  </ul>
{% endblock content %}
</body>
</html>

cat/templates/cat/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends "cat/base.html" %}
</head>
<body>
{% block content %}

    <p>Topics</p>

    <ul>
        {% for topic in topics %}
            <li>
                <a href="{% url 'cat:topic' topic.id %}">{{ topic }}</a>
            </li>
        {% empty %}
            <li>No topics have been added yet :(</li>
        {% endfor %}
    </ul>

    <a href="{% url 'cat:new_topic' %}">Add a new topic</a>

{% endblock content %}
</body>
</html>